language: node_js
node_js:
  - "iojs"


notifications:
  email:
    recipients:
      - marcin.sokol@capgemini.com
      - mateusz.skawinski@capgemini.com
    on_success: change
    on_failure: change


script:
  - cd iot/src/main/client
  - npm install -g bower
  - npm install gulp
  - npm install glob
  - npm install coveralls --save-dev
  - npm install karma-coveralls --save-dev
  - npm install
  - npm test

after_success:
    - cat ./test-output/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
