language: node_js
node_js:
  - "iojs"

notifications:
  email:
    recipients:
      - marcin.sokol@capgemini.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always


before_script:
  - cd iot/src/main/client
  - npm install -g bower
  - npm install -g gulp

script:
  - npm test