language: node_js
node_js:
  - "iojs"

notifications:
  email:
    recipients:
      - marcin.sokol@capgemini.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

script:
  - cd iot/src/main/client
  - npm install -g bower
  - npm install gulp
  - npm install -g glob
  - npm install -g
  - npm test