language: node_js
node_js:
  - "iojs"


notifications:
  email:
    recipients:
      - marcin.sokol@capgemini.com
      - mateusz.skawinski@capgemini.com
    on_success: change
    on_failure: change


script:
  - cd iot/src/main/client
  - npm install -g bower
  - npm install gulp
  - npm install glob
  - npm install nodeunit jscoverage coveralls --save-dev
  - npm install
  - npm test